name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:
      - v*.*.*

jobs:
  check:
    uses: ./.github/workflows/check.yml

  publish:
    uses: ./.github/workflows/publish.yml
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    needs: check
    with:
      version: ${{ github.ref_name }}
    secrets:
      crates-io-token: ${{ secrets.CRATES_IO_TOKEN }}
